language: android

android:
  components:
      # Uncomment the lines below if you want to
      # use the latest revision of Android SDK Tools
      - tools
      - platform-tools

      # The BuildTools version used by your project
      - build-tools-23.0.3

      # The SDK version used to compile your project
      - android-23

      # Additional components
      #- extra-google-google_play_services
      #- extra-google-m2repository
      - extra-android-m2repository

      # Specify at least one system image,
      # if you need to run emulator(s) during your tests
      #- sys-img-armeabi-v7a-android-23
      #licenses:
              #- 'android-sdk-license-.+'

cache:
  directories:
    - $HOME/.gradle/caches/2.10
# Remember to change 2.10 with your gradle version if you are using a different one and remember also that the version is specified in the file gradle-wrapper.properties in your root gradle folder.
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

# Emulator Management: Create, Start and Wait
before_script:
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - curl http://is.gd/android_wait_for_emulator > android-wait-for-emulator
    - chmod u+x android-wait-for-emulator
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

# script: "./gradlew build"

sudo: false

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

#cache:
#  directories:
#    - $HOME/.gradle


##--------------------------------------------------------------------------------
## After test cases written

#env:
#    matrix:
#        - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a
#        - ANDROID_TARGET=android-16 ANDROID_ABI=armeabi-v7a

#before_script:
#    - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
#    - emulator -avd test -no-skin -no-audio -no-window &amp;

#script:
#  - ./gradlew check -PdisablePreDex --continue --stacktrace
#  - android-wait-for-emulator
#  - adb devices
#  - adb shell input keyevent 82 &amp;
#  - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace

#after_failure:
#  - wget http://imgur.com/tools/imgurbash.sh
#  - chmod a+x imgurbash.sh
#  - adb shell screencap -p | sed 's/\r$//' &gt; screen.png
#  - ./imgurbash.sh screen.png
#  - pandoc builder/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'

#after_success:
#  - ./gradlew jacocoFullReport
#  - pip install --user codecov
#  - codecov

